# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logFactorial <- function(n) {
    .Call(`_countirt_logFactorial`, n)
}

computeA <- function(lambda, mu, nu, log_Z, min_iter) {
    .Call(`_countirt_computeA`, lambda, mu, nu, log_Z, min_iter)
}

computeB <- function(lambda, mu, nu, log_Z, min_iter) {
    .Call(`_countirt_computeB`, lambda, mu, nu, log_Z, min_iter)
}

computeQ <- function(lambda, mu, nu, min_iter) {
    .Call(`_countirt_computeQ`, lambda, mu, nu, min_iter)
}

computeW <- function(lambda, mu, nu, min_iter) {
    .Call(`_countirt_computeW`, lambda, mu, nu, min_iter)
}

computeR <- function(lambda, mu, nu, log_Z, min_iter) {
    .Call(`_countirt_computeR`, lambda, mu, nu, log_Z, min_iter)
}

computepp <- function(dens, quad_weight, marg_prob) {
    .Call(`_countirt_computepp`, dens, quad_weight, marg_prob)
}

computepp_allnodes <- function(dens, quad_weight, marg_prob) {
    .Call(`_countirt_computepp_allnodes`, dens, quad_weight, marg_prob)
}

computer <- function(resp, pp) {
    .Call(`_countirt_computer`, resp, pp)
}

computer_allnodes <- function(resp, pp) {
    .Call(`_countirt_computer_allnodes`, resp, pp)
}

computef <- function(pp) {
    .Call(`_countirt_computef`, pp)
}

computef_allnodes <- function(pp) {
    .Call(`_countirt_computef_allnodes`, pp)
}

computeh <- function(resp, pp) {
    .Call(`_countirt_computeh`, resp, pp)
}

computeh_allnodes <- function(resp, pp) {
    .Call(`_countirt_computeh_allnodes`, resp, pp)
}

interp_from_grid <- function(mu, nu, grid_long, mu0, nu0) {
    .Call(`_countirt_interp_from_grid`, mu, nu, grid_long, mu0, nu0)
}

interp_from_grid_v <- function(mu, nu, grid_long, mu0_v, nu0_v) {
    .Call(`_countirt_interp_from_grid_v`, mu, nu, grid_long, mu0_v, nu0_v)
}

interp_from_grid_m <- function(mu, nu, grid_long, mu0_m, nu0_m) {
    .Call(`_countirt_interp_from_grid_m`, mu, nu, grid_long, mu0_m, nu0_m)
}

interp_from_grid_lin_m <- function(mu, nu, grid_long, mu0_m, nu0_m) {
    .Call(`_countirt_interp_from_grid_lin_m`, mu, nu, grid_long, mu0_m, nu0_m)
}

dcmp_cpp <- function(data, mu, nu, logprob, all_mus_lambda, all_nus_lambda, all_mus_logZ, all_nus_logZ, grid_long_log_lambda, grid_long_logZ) {
    .Call(`_countirt_dcmp_cpp`, data, mu, nu, logprob, all_mus_lambda, all_nus_lambda, all_mus_logZ, all_nus_logZ, grid_long_log_lambda, grid_long_logZ)
}

grad_cmp_cpp <- function(alphas, deltas, disps, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, grid_W_long, grid_R_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_cpp`, alphas, deltas, disps, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, grid_W_long, grid_R_long, max_mu, min_mu)
}

grad_cmp_fixdisps_cpp <- function(alphas, deltas, disps, nodes, r, f, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, max_mu) {
    .Call(`_countirt_grad_cmp_fixdisps_cpp`, alphas, deltas, disps, nodes, r, f, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, max_mu)
}

grad_cmp_fixalphas_cpp <- function(alphas, deltas, disps, nodes, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu) {
    .Call(`_countirt_grad_cmp_fixalphas_cpp`, alphas, deltas, disps, nodes, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu)
}

grad_cmp_logdisps_cpp <- function(alphas, deltas, disps, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu) {
    .Call(`_countirt_grad_cmp_logdisps_cpp`, alphas, deltas, disps, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu)
}

grad_cmp_samedisp_cpp <- function(alphas, deltas, disp, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, grid_W_long, grid_R_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_samedisp_cpp`, alphas, deltas, disp, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, grid_W_long, grid_R_long, max_mu, min_mu)
}

grad_cmp_samedisp_cpp_lininterp <- function(alphas, deltas, disp, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_W_long, grid_R_long, max_mu) {
    .Call(`_countirt_grad_cmp_samedisp_cpp_lininterp`, alphas, deltas, disp, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_W_long, grid_R_long, max_mu)
}

grad_cmp_samealpha_cpp <- function(alpha, deltas, disps, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu) {
    .Call(`_countirt_grad_cmp_samealpha_cpp`, alpha, deltas, disps, nodes, weights, r, f, h, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu)
}

ell_cmp_cpp <- function(alphas, deltas, disps, nodes, r, f, h, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu) {
    .Call(`_countirt_ell_cmp_cpp`, alphas, deltas, disps, nodes, r, f, h, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu)
}

e_values_cpp <- function(data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_e_values_cpp`, data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

e_values_cpp_lininterp <- function(data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu) {
    .Call(`_countirt_e_values_cpp_lininterp`, data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu)
}

marg_ll_cpp <- function(data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_marg_ll_cpp`, data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

marg_ll_cmp_with_pcov_cpp <- function(data, alphas, deltas, disps, betas, p_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_marg_ll_cmp_with_pcov_cpp`, data, alphas, deltas, disps, betas, p_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

marg_ll_cmp_with_icov_delta_cpp <- function(data, alphas, delta, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_delta_cpp`, data, alphas, delta, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

marg_ll_cmp_with_icov_alpha_cpp <- function(data, alpha, deltas, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_alpha_cpp`, data, alpha, deltas, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

marg_ll_cmp_with_icov_nu_cpp <- function(data, alphas, deltas, disp, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_nu_cpp`, data, alphas, deltas, disp, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

marg_ll_cmp_with_icov_all_cpp <- function(data, alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_all_cpp`, data, alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

marg_ll_cmp_with_icov_alpha_nu_cpp <- function(data, alpha, deltas, disp, betas_alpha, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_alpha_nu_cpp`, data, alpha, deltas, disp, betas_alpha, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

marg_ll_cmp_with_icov_delta_nu_cpp <- function(data, alphas, delta, disp, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_delta_nu_cpp`, data, alphas, delta, disp, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

marg_ll_cmp_with_icov_alpha_delta_cpp <- function(data, alpha, delta, disps, betas_alpha, betas_delta, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_marg_ll_cmp_with_icov_alpha_delta_cpp`, data, alpha, delta, disps, betas_alpha, betas_delta, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

marg_ll_cpp_lininterp <- function(data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long) {
    .Call(`_countirt_marg_ll_cpp_lininterp`, data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long)
}

grad_cmp_newem_cpp <- function(alphas, deltas, disps, data, exp_abilities, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_newem_cpp`, alphas, deltas, disps, data, exp_abilities, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_newem_cpp2 <- function(alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_newem_cpp2`, alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_pcov_cpp <- function(alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_pcov_cpp`, alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_delta_cpp <- function(alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_cpp`, alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_alpha_cpp <- function(alpha, deltas, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_cpp`, alpha, deltas, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_nu_cpp <- function(alphas, deltas, disp, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_nu_cpp`, alphas, deltas, disp, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_with_icov_all_cpp <- function(alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_all_cpp`, alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_with_icov_alpha_nu_cpp <- function(alpha, deltas, disp, betas_alpha, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_nu_cpp`, alpha, deltas, disp, betas_alpha, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_with_icov_delta_nu_cpp <- function(alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_nu_cpp`, alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_with_icov_alpha_delta_cpp <- function(alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_delta_cpp`, alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_fixdisps_newem_cpp <- function(alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_fixdisps_newem_cpp`, alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_pcov_fixdisps_cpp <- function(alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_pcov_fixdisps_cpp`, alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_delta_fixdisps_cpp <- function(alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_fixdisps_cpp`, alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_alpha_fixdisps_cpp <- function(alpha, deltas, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_fixdisps_cpp`, alpha, deltas, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_alpha_delta_fixdisps_cpp <- function(alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_delta_fixdisps_cpp`, alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_fixalphas_newem_cpp <- function(alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_fixalphas_newem_cpp`, alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_pcov_fixalphas_cpp <- function(alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_pcov_fixalphas_cpp`, alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_delta_fixalphas_cpp <- function(alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_fixalphas_cpp`, alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_nu_fixalphas_cpp <- function(alphas, deltas, disp, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_nu_fixalphas_cpp`, alphas, deltas, disp, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_with_icov_delta_nu_fixalphas_cpp <- function(alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_nu_fixalphas_cpp`, alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_samedisps_newem_cpp <- function(alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_samedisps_newem_cpp`, alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_pcov_samedisps_cpp <- function(alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_pcov_samedisps_cpp`, alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_delta_samedisps_cpp <- function(alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_samedisps_cpp`, alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_alpha_samedisps_cpp <- function(alpha, deltas, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_samedisps_cpp`, alpha, deltas, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_alpha_delta_samedisps_cpp <- function(alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_alpha_delta_samedisps_cpp`, alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_samealphas_newem_cpp <- function(alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_samealphas_newem_cpp`, alphas, deltas, disps, data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_pcov_samealphas_cpp <- function(alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_pcov_samealphas_cpp`, alphas, deltas, disps, betas, data, p_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_delta_samealphas_cpp <- function(alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_samealphas_cpp`, alphas, delta, disps, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

grad_cmp_with_icov_nu_samealphas_cpp <- function(alphas, deltas, disp, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_nu_samealphas_cpp`, alphas, deltas, disp, betas, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_cmp_with_icov_delta_nu_samealphas_cpp <- function(alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_grad_cmp_with_icov_delta_nu_samealphas_cpp`, alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

grad_ll_cmp_ability_1P_cpp <- function(ability, alphas, deltas, disps, data, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_grad_ll_cmp_ability_1P_cpp`, ability, alphas, deltas, disps, data, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, max_mu, min_mu)
}

ell_cmp_newem_cpp <- function(alphas, deltas, disps, data, exp_abilities, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_ell_cmp_newem_cpp`, alphas, deltas, disps, data, exp_abilities, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

ell_cmp_with_pcov_cpp <- function(alphas, deltas, disps, betas, data, p_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_ell_cmp_with_pcov_cpp`, alphas, deltas, disps, betas, data, p_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

ell_cmp_with_icov_delta_cpp <- function(alphas, delta, disps, betas, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_ell_cmp_with_icov_delta_cpp`, alphas, delta, disps, betas, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

ell_cmp_with_icov_alpha_cpp <- function(alpha, deltas, disps, betas, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_ell_cmp_with_icov_alpha_cpp`, alpha, deltas, disps, betas, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

ell_cmp_with_icov_nu_cpp <- function(alphas, deltas, disp, betas, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_ell_cmp_with_icov_nu_cpp`, alphas, deltas, disp, betas, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

ell_cmp_with_icov_all_cpp <- function(alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_ell_cmp_with_icov_all_cpp`, alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

ell_cmp_with_icov_alpha_nu_cpp <- function(alpha, deltas, disp, betas_alpha, betas_logdisp, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_ell_cmp_with_icov_alpha_nu_cpp`, alpha, deltas, disp, betas_alpha, betas_logdisp, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

ell_cmp_with_icov_delta_nu_cpp <- function(alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_ell_cmp_with_icov_delta_nu_cpp`, alphas, delta, disp, betas_delta, betas_logdisp, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu, max_nu, min_nu)
}

ell_cmp_with_icov_alpha_delta_cpp <- function(alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu) {
    .Call(`_countirt_ell_cmp_with_icov_alpha_delta_cpp`, alpha, delta, disps, betas_alpha, betas_delta, data, i_cov_data, PPs, weights, nodes, grid_mus, grid_nus, grid_cmp_var_long, grid_log_lambda_long, grid_logZ_long, max_mu, min_mu)
}

e_values_newem_cpp <- function(data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_e_values_newem_cpp`, data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

e_values_newem_cpp2 <- function(data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_e_values_newem_cpp2`, data, alphas, deltas, disps, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

estep_cmp_with_icov_delta_cpp <- function(data, alphas, delta, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_estep_cmp_with_icov_delta_cpp`, data, alphas, delta, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

estep_cmp_with_icov_alpha_cpp <- function(data, alpha, deltas, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_estep_cmp_with_icov_alpha_cpp`, data, alpha, deltas, disps, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

estep_cmp_with_icov_nu_cpp <- function(data, alphas, deltas, disp, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_estep_cmp_with_icov_nu_cpp`, data, alphas, deltas, disp, betas, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

estep_cmp_with_icov_all_cpp <- function(data, alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_estep_cmp_with_icov_all_cpp`, data, alpha, delta, disp, betas_alpha, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

estep_cmp_with_icov_alpha_nu_cpp <- function(data, alpha, deltas, disp, betas_alpha, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_estep_cmp_with_icov_alpha_nu_cpp`, data, alpha, deltas, disp, betas_alpha, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

estep_cmp_with_icov_delta_nu_cpp <- function(data, alphas, delta, disp, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_estep_cmp_with_icov_delta_nu_cpp`, data, alphas, delta, disp, betas_delta, betas_logdisp, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

estep_cmp_with_icov_alpha_delta_cpp <- function(data, alpha, delta, disps, betas_alpha, betas_delta, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu) {
    .Call(`_countirt_estep_cmp_with_icov_alpha_delta_cpp`, data, alpha, delta, disps, betas_alpha, betas_delta, i_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu, max_nu, min_nu)
}

estep_cmp_with_pcov_cpp <- function(data, alphas, deltas, disps, betas, p_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu) {
    .Call(`_countirt_estep_cmp_with_pcov_cpp`, data, alphas, deltas, disps, betas, p_cov_data, nodes, weights, grid_mus, grid_nus, grid_logZ_long, grid_log_lambda_long, max_mu, min_mu)
}

